version: 2.0
jobs:
    prod-deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            - run:
                name: "setup heroku command"
                command: bash .circleci/setup_heroku.sh
            - run:
                name: "push container to registry.heroku.com"
                command: bash .circleci/prod_deploy.sh
workflows:
    version: 2
    productionflow:
        jobs:
            - prod-deploy:
                context: heroku
                filters:
                    branches:
                        only:
                            - master
